# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.

# The CMake executable.
CMAKE_COMMAND = /data/data/ru.iiec.cxxdroid/files/bin/cmake

# The command to remove a file.
RM = /data/data/ru.iiec.cxxdroid/files/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /storage/emulated/0/Documents/Cxxdroid/cpp/Tetris

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /storage/emulated/0/Documents/Cxxdroid/cpp/Tetris

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /storage/emulated/0/Documents/Cxxdroid/cpp/Tetris/CMakeFiles /storage/emulated/0/Documents/Cxxdroid/cpp/Tetris//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /storage/emulated/0/Documents/Cxxdroid/cpp/Tetris/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Tetris

# Build rule for target.
Tetris: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tetris
.PHONY : Tetris

# fast build rule for target.
Tetris/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/build
.PHONY : Tetris/fast

src/Fonts.o: src/Fonts.cpp.o
.PHONY : src/Fonts.o

# target to build an object file
src/Fonts.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/src/Fonts.cpp.o
.PHONY : src/Fonts.cpp.o

src/Fonts.i: src/Fonts.cpp.i
.PHONY : src/Fonts.i

# target to preprocess a source file
src/Fonts.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/src/Fonts.cpp.i
.PHONY : src/Fonts.cpp.i

src/Fonts.s: src/Fonts.cpp.s
.PHONY : src/Fonts.s

# target to generate assembly for a file
src/Fonts.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/src/Fonts.cpp.s
.PHONY : src/Fonts.cpp.s

src/Images.o: src/Images.cpp.o
.PHONY : src/Images.o

# target to build an object file
src/Images.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/src/Images.cpp.o
.PHONY : src/Images.cpp.o

src/Images.i: src/Images.cpp.i
.PHONY : src/Images.i

# target to preprocess a source file
src/Images.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/src/Images.cpp.i
.PHONY : src/Images.cpp.i

src/Images.s: src/Images.cpp.s
.PHONY : src/Images.s

# target to generate assembly for a file
src/Images.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/src/Images.cpp.s
.PHONY : src/Images.cpp.s

src/SdlInit.o: src/SdlInit.cpp.o
.PHONY : src/SdlInit.o

# target to build an object file
src/SdlInit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/src/SdlInit.cpp.o
.PHONY : src/SdlInit.cpp.o

src/SdlInit.i: src/SdlInit.cpp.i
.PHONY : src/SdlInit.i

# target to preprocess a source file
src/SdlInit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/src/SdlInit.cpp.i
.PHONY : src/SdlInit.cpp.i

src/SdlInit.s: src/SdlInit.cpp.s
.PHONY : src/SdlInit.s

# target to generate assembly for a file
src/SdlInit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/src/SdlInit.cpp.s
.PHONY : src/SdlInit.cpp.s

src/Start.o: src/Start.cpp.o
.PHONY : src/Start.o

# target to build an object file
src/Start.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/src/Start.cpp.o
.PHONY : src/Start.cpp.o

src/Start.i: src/Start.cpp.i
.PHONY : src/Start.i

# target to preprocess a source file
src/Start.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/src/Start.cpp.i
.PHONY : src/Start.cpp.i

src/Start.s: src/Start.cpp.s
.PHONY : src/Start.s

# target to generate assembly for a file
src/Start.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/src/Start.cpp.s
.PHONY : src/Start.cpp.s

src/StartScreen.o: src/StartScreen.cpp.o
.PHONY : src/StartScreen.o

# target to build an object file
src/StartScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/src/StartScreen.cpp.o
.PHONY : src/StartScreen.cpp.o

src/StartScreen.i: src/StartScreen.cpp.i
.PHONY : src/StartScreen.i

# target to preprocess a source file
src/StartScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/src/StartScreen.cpp.i
.PHONY : src/StartScreen.cpp.i

src/StartScreen.s: src/StartScreen.cpp.s
.PHONY : src/StartScreen.s

# target to generate assembly for a file
src/StartScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/src/StartScreen.cpp.s
.PHONY : src/StartScreen.cpp.s

src/abs/IDraw.o: src/abs/IDraw.cpp.o
.PHONY : src/abs/IDraw.o

# target to build an object file
src/abs/IDraw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/src/abs/IDraw.cpp.o
.PHONY : src/abs/IDraw.cpp.o

src/abs/IDraw.i: src/abs/IDraw.cpp.i
.PHONY : src/abs/IDraw.i

# target to preprocess a source file
src/abs/IDraw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/src/abs/IDraw.cpp.i
.PHONY : src/abs/IDraw.cpp.i

src/abs/IDraw.s: src/abs/IDraw.cpp.s
.PHONY : src/abs/IDraw.s

# target to generate assembly for a file
src/abs/IDraw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/src/abs/IDraw.cpp.s
.PHONY : src/abs/IDraw.cpp.s

src/abs/Screen.o: src/abs/Screen.cpp.o
.PHONY : src/abs/Screen.o

# target to build an object file
src/abs/Screen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/src/abs/Screen.cpp.o
.PHONY : src/abs/Screen.cpp.o

src/abs/Screen.i: src/abs/Screen.cpp.i
.PHONY : src/abs/Screen.i

# target to preprocess a source file
src/abs/Screen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/src/abs/Screen.cpp.i
.PHONY : src/abs/Screen.cpp.i

src/abs/Screen.s: src/abs/Screen.cpp.s
.PHONY : src/abs/Screen.s

# target to generate assembly for a file
src/abs/Screen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/src/abs/Screen.cpp.s
.PHONY : src/abs/Screen.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tetris.dir/build.make CMakeFiles/Tetris.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Tetris"
	@echo "... src/Fonts.o"
	@echo "... src/Fonts.i"
	@echo "... src/Fonts.s"
	@echo "... src/Images.o"
	@echo "... src/Images.i"
	@echo "... src/Images.s"
	@echo "... src/SdlInit.o"
	@echo "... src/SdlInit.i"
	@echo "... src/SdlInit.s"
	@echo "... src/Start.o"
	@echo "... src/Start.i"
	@echo "... src/Start.s"
	@echo "... src/StartScreen.o"
	@echo "... src/StartScreen.i"
	@echo "... src/StartScreen.s"
	@echo "... src/abs/IDraw.o"
	@echo "... src/abs/IDraw.i"
	@echo "... src/abs/IDraw.s"
	@echo "... src/abs/Screen.o"
	@echo "... src/abs/Screen.i"
	@echo "... src/abs/Screen.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

